# Generated by Django 2.0.1 on 2018-01-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aarticle', '0003_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
